import { test, expect } from '@playwright/test';

test('desktop: complete shortened diagnostic with investment mask and CRM submission', async ({ page }) => {
  const errors: string[] = [];
  let submittedLead: Record<string, string> | undefined;
  page.on('pageerror', error => errors.push(error.message));
  await page.route('**/api/leads', async route => {
    submittedLead = route.request().postDataJSON();
    await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ success: true }) });
  });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto('/?utm_source=browser-test&utm_campaign=validation');
  await page.getByRole('button', { name: 'Só essenciais', exact: true }).click();
  await expect(page.getByRole('heading', { level: 1 })).toBeVisible();
  await page.screenshot({ path: 'test-results/desktop.png' });
  await page.getByRole('link', { name: /Iniciar diagnóstico SAC/ }).first().click();
  const panel = page.locator('#diagnostic-panel');
  await panel.getByRole('button', { name: 'Continuar', exact: true }).click();
  await expect(panel.getByRole('alert')).toHaveCount(2);
  await panel.getByRole('radio', { name: 'Indústria', exact: true }).check();
  await panel.locator('select').selectOption('Alimentos e bebidas');
  await panel.getByRole('button', { name: 'Continuar', exact: true }).click();
  await panel.getByRole('radio', { name: 'R$ 1 milhão a R$ 3 milhões/mês', exact: true }).check();
  await panel.getByRole('radio', { name: '51 a 100', exact: true }).check();
  await page.reload();
  await expect(panel.getByRole('radio', { name: '51 a 100', exact: true })).toBeChecked();
  await panel.getByRole('button', { name: 'Voltar', exact: true }).click();
  await expect(panel.getByRole('radio', { name: 'Indústria', exact: true })).toBeChecked();
  await panel.getByRole('button', { name: 'Continuar', exact: true }).click();
  await panel.getByRole('button', { name: 'Continuar', exact: true }).click();
  await panel.locator('fieldset').nth(0).getByRole('radio').nth(1).check();
  await panel.locator('fieldset').nth(1).getByRole('radio').nth(2).check();
  await panel.getByRole('button', { name: 'Continuar', exact: true }).click();
  await panel.locator('select').selectOption('Prospecção dos representantes');
  await panel.getByRole('radio', { name: '1 a 5', exact: true }).check();
  await panel.getByRole('button', { name: 'Continuar', exact: true }).click();
  await panel.getByRole('radio').first().check();
  await panel.getByRole('button', { name: 'Continuar', exact: true }).click();
  await panel.getByRole('radio', { name: 'Sou o principal decisor', exact: true }).check();
  await panel.locator('select').selectOption('Diretor Comercial');
  await panel.getByRole('button', { name: 'Continuar', exact: true }).click();
  await panel.getByRole('radio', { name: 'Nos próximos 30 dias', exact: true }).check();
  const investment = panel.getByRole('textbox', { name: 'Qual nível de investimento sua empresa tem capacidade de avaliar hoje?' });
  await investment.fill('15000');
  await expect(investment).toHaveValue('R$ 15.000');
  await panel.getByRole('button', { name: 'Continuar', exact: true }).click();
  await panel.getByRole('button', { name: 'Finalizar meu diagnóstico SAC', exact: true }).click();
  await expect(panel.getByRole('alert')).toHaveCount(7);
  await panel.getByRole('textbox', { name: 'Nome completo' }).fill('Ana Silva');
  await panel.getByRole('textbox', { name: 'Empresa', exact: true }).fill('Empresa Teste');
  await panel.getByRole('textbox', { name: 'WhatsApp' }).fill('+5511999999999');
  await panel.getByRole('textbox', { name: 'E-mail corporativo' }).fill('ana@example.com');
  await panel.getByRole('textbox', { name: 'Cidade da sede' }).fill('São Paulo');
  await panel.getByRole('combobox', { name: 'Estado' }).selectOption('SP');
  await panel.getByRole('checkbox').check();
  await panel.getByRole('button', { name: 'Finalizar meu diagnóstico SAC', exact: true }).click();
  await expect(panel.getByRole('heading', { name: 'Diagnóstico recebido.' })).toBeVisible();
  expect(submittedLead?.phone).toBe('+5511999999999');
  expect(submittedLead?.name).toBe('Ana Silva');
  expect(await page.evaluate(() => sessionStorage.getItem('sac-diagnostic-v1'))).toBeNull();
  expect(await page.evaluate(() => (window as any).dataLayer)).toBeUndefined();
  expect(errors).toEqual([]);
});

test('mobile: navigation, accordion, consent and viewport overflow', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await page.getByRole('button', { name: 'Aceitar métricas', exact: true }).click();
  await page.screenshot({ path: 'test-results/mobile.png' });
  await page.getByRole('button', { name: 'Abrir menu' }).click();
  await page.getByRole('link', { name: 'Para quem', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Abrir menu' })).toBeVisible();
  await expect(page).toHaveURL(/#para-quem/);
  await page.getByRole('button', { name: /Preciso trocar meu CRM/ }).click();
  await expect(page.locator('#faq-answer-2')).toBeVisible();
  await expect(page.locator('#faq-answer-0')).toBeHidden();
  await page.getByRole('button', { name: 'Privacidade', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  for (const width of [320, 390, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 900 });
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth);
    expect(overflow, 'horizontal overflow at ' + width).toBe(false);
  }
  expect(await page.evaluate(() => (window as any).dataLayer.some((item: any) => item.event === 'lp_view'))).toBe(true);
});
